# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16sjDj1u_ORcjQ9eHQQhSTKLZPj_74XzH
"""

import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix, classification_report
import numpy as np
import pandas as pd

# Assuming you have these variables from your model training
# y_true = actual test labels
# y_pred = predicted labels from your model

# Sample data (replace with your actual data)
# For demonstration purposes, let's create some sample data
np.random.seed(42)
y_true = np.random.randint(0, 5, 100)  # 100 samples, 5 classes
y_pred = y_true + np.random.randint(-1, 2, 100)  # Add some noise to predictions
y_pred = np.clip(y_pred, 0, 4)  # Ensure predictions stay within class range

# Class names (replace with your actual class names)
class_names = ['Class 0', 'Class 1', 'Class 2', 'Class 3', 'Class 4']

def plot_confusion_matrix(y_true, y_pred, class_names, title='Confusion Matrix'):
    """
    Plot a detailed confusion matrix with accuracy metrics

    Parameters:
    y_true: array-like of true labels
    y_pred: array-like of predicted labels
    class_names: list of class names
    title: title for the plot
    """
    # Calculate confusion matrix
    cm = confusion_matrix(y_true, y_pred)

    # Calculate accuracy metrics
    accuracy = np.trace(cm) / np.sum(cm)
    precision = np.diag(cm) / np.sum(cm, axis=0)
    recall = np.diag(cm) / np.sum(cm, axis=1)
    f1_score = 2 * (precision * recall) / (precision + recall)

    # Create figure with subplots
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 6))

    # Plot confusion matrix
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', ax=ax1,
                xticklabels=class_names, yticklabels=class_names)
    ax1.set_xlabel('Predicted Label')
    ax1.set_ylabel('True Label')
    ax1.set_title(f'{title}\nOverall Accuracy: {accuracy:.2%}')

    # Create metrics table
    metrics_data = []
    for i, class_name in enumerate(class_names):
        metrics_data.append([
            class_name,
            f'{precision[i]:.2%}' if not np.isnan(precision[i]) else 'N/A',
            f'{recall[i]:.2%}' if not np.isnan(recall[i]) else 'N/A',
            f'{f1_score[i]:.2%}' if not np.isnan(f1_score[i]) else 'N/A',
            cm[i, i]  # True positives for each class
        ])

    # Add overall metrics
    metrics_data.append([
        'Overall',
        f'{np.nanmean(precision):.2%}',
        f'{np.nanmean(recall):.2%}',
        f'{np.nanmean(f1_score):.2%}',
        np.trace(cm)
    ])

    # Create metrics table
    ax2.axis('off')
    table = ax2.table(cellText=metrics_data,
                     colLabels=['Class', 'Precision', 'Recall', 'F1-Score', 'Correct'],
                     cellLoc='center',
                     loc='center')
    table.auto_set_font_size(False)
    table.set_fontsize(10)
    table.scale(1, 1.5)
    ax2.set_title('Classification Metrics')

    plt.tight_layout()
    plt.show()

    # Print detailed classification report
    print("Detailed Classification Report:")
    print(classification_report(y_true, y_pred, target_names=class_names))

    return cm, accuracy

# Plot the confusion matrix
cm, accuracy = plot_confusion_matrix(y_true, y_pred, class_names, 'Body Language Classification')

# Additional: Normalized confusion matrix
def plot_normalized_confusion_matrix(y_true, y_pred, class_names):
    """
    Plot normalized confusion matrix
    """
    cm = confusion_matrix(y_true, y_pred)
    cm_normalized = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]

    plt.figure(figsize=(10, 8))
    sns.heatmap(cm_normalized, annot=True, fmt='.2%', cmap='Reds',
                xticklabels=class_names, yticklabels=class_names)
    plt.xlabel('Predicted Label')
    plt.ylabel('True Label')
    plt.title('Normalized Confusion Matrix\n(Values represent percentage of true class)')
    plt.tight_layout()
    plt.show()

# Plot normalized confusion matrix
plot_normalized_confusion_matrix(y_true, y_pred, class_names)

# Additional: Class distribution plot
def plot_class_distribution(y_true, y_pred, class_names):
    """
    Plot class distribution and prediction comparison
    """
    true_counts = np.bincount(y_true, minlength=len(class_names))
    pred_counts = np.bincount(y_pred, minlength=len(class_names))

    x = np.arange(len(class_names))
    width = 0.35

    plt.figure(figsize=(12, 6))
    plt.bar(x - width/2, true_counts, width, label='True Distribution', alpha=0.7)
    plt.bar(x + width/2, pred_counts, width, label='Predicted Distribution', alpha=0.7)

    plt.xlabel('Classes')
    plt.ylabel('Count')
    plt.title('Class Distribution: True vs Predicted')
    plt.xticks(x, class_names)
    plt.legend()
    plt.grid(axis='y', alpha=0.3)
    plt.tight_layout()
    plt.show()

# Plot class distribution
plot_class_distribution(y_true, y_pred, class_names)